### ISSUE TITLE
An issue about Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by hewigovens** [makerdao/scd-cdp-portal#15]
Hi,

Trust Wallet changed ethereum rpc endpoint from infura to `https://ethereum-rpc.trustwalletapp.com/`(it's a load balancer) recently, user may not able to load their cdp history.
here is the error screenshot from Safari console:

![screen shot 2019-01-20 at 11 41 45](https://user-images.githubusercontent.com/360470/51435001-68cf2480-1ca8-11e9-9f12-bf67b38566c4.png)

It may be awkward to ask, but app is in production, could you please help to add `ethereum-rpc.trustwalletapp.com` to allowed origin list? 

Thanks

**Comment by levity** [comment]
Hi! If I’m understanding this correctly, this is a change that Trust Wallet
has to do on the server side.

**Comment by hewigovens** [comment]
Thanks for your reply, it seems the error is not thrown by cdp portal
