### ISSUE TITLE
Cannot unlock DAI and MKR

### ISSUE THREAD

**Issue by rossbulat** [makerdao/scd-cdp-portal#20]
Have been testing the CDP process and currently unable to unlock DAI and MKR.

Upon signing the transaction with MetaMask, the transaction is not found on Etherscan, and the unlock UI is constantly pending:

<img width="354" alt="screenshot 2019-03-08 at 10 27 25" src="https://user-images.githubusercontent.com/13929023/54003344-d9fd6500-418c-11e9-8780-80bc6825fc31.png">

<img width="393" alt="screenshot 2019-03-08 at 10 28 47" src="https://user-images.githubusercontent.com/13929023/54003374-fa2d2400-418c-11e9-934c-b37388da2cc7.png">

**Comment by pcatana** [comment]
It looks like it might be a problem with Metamask. Make sure that your previous Metamask transactions are mined before you sign a new one. And if it's stuck, reset Metamask by reinstalling it.  Make sure to have your seed phrase backed up before you do that.

**Comment by rossbulat** [comment]
Thank you, yes this solved the issue. Looks like a MetaMask bug of some sort.
