### ISSUE TITLE
KeepKey Integration

### ISSUE THREAD

**Issue by keepkeyjon** [makerdao/scd-cdp-portal#33]
Can I talk you into doing a KeepKey integration?

With this firmware PR, I think the hardware-wallet UX could be really compelling: https://github.com/keepkey/keepkey-firmware/pull/103

**Comment by levity** [comment]
This seems pretty interesting, but to be honest, most of our focus is on shipping Multi-Collateral Dai at the moment. We don't really have bandwidth for changes to the SCD portal beyond bug fixes and better support for mobile browsers. But pull requests are always welcome :)

**Comment by keepkeyjon** [comment]
Would you have more interest if I did the same for MCD?

**Comment by levity** [comment]
I think so? We would have to understand more about what you're trying to
integrate into your wallet firmware here. We're developing the portal in a
way that assumes "dumb" wallets, i.e. they just provide addresses and sign
arbitrary transactions. But it seems like you're trying to make the wallet
"smarter", which is cool, but would probably be more work to integrate.

**Comment by keepkeyjon** [comment]
The firmware change adds logic to detect messages to these contracts and pull out the fields from the data to make a human-readable message, without changing the external API of the device compared to a "dumb" wallet.

A user with an older firmware, without support for this would need to confirm the raw hex data:

`Confirm Ethereum Data: 1edf0c1e...`

But if they upgraded they'd see:

`MakerDAO: Deposit 2 ETH into CDP 1234 and withdraw 156 DAI?`

without any changes to the client.

**Comment by levity** [comment]
Ah, I see. That's pretty cool!

**Comment by keepkeyjon** [comment]
We just released firmware support for this. Would love it if you'd check it out :) https://medium.com/shapeshift-stories/makerdao-on-keepkey-discover-defi-3d53986c1d14
